DashBoard/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', index, name='index'),
    path('login', Login.as_view(), name='login'),
    path('register', Register.as_view(), name='register'),
    path('logout', Logout.as_view(), name='logout'),

    path('dashboard', CheckHealth.as_view(), name='dashboard'),

    path('history', HistoryView.as_view(), name='history'),
    path('history/<int:pk>', PrintResult.as_view(), name='printHistory'),

    path('user', Users.as_view(), name='users'),
    path('user/<int:pk>', UserDetail.as_view(), name='userDetail'),
]

HDPuRF/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DashBoard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DashBoard/models.py
from django.db import models


# Create your models here.
class History(models.Model):
    SEX = (
        (0, 'Female'),
        (1, 'Male')
    )
    CP = (
        (0, 'typical angina'),
        (1, 'atypical angina'),
        (2, 'non-anginal pain'),
        (3, 'asymptomatic')
    )
    RESTECG = (
        (0, 'Normal'),
        (1, 'ST-T wave abnormality'),
        (2, 'Left ventricular hypertrophy')
    )
    EXANG = (
        (0, 'No'),
        (1, 'Yes')
    )
    SLOPE = (
        (0, 'Upsloping'),
        (1, 'Flat'),
        (2, 'Downsloping')
    )
    THAL = (
        (3, 'Normal'),
        (6, 'Fixed defect'),
        (7, 'Reversable defect')
    )
    TARGET = (
        (1, 'No'),
        (2, 'Yes')
    )
    FBS = (
        (0, 'False'),
        (1, 'True')
    )
    EXANG = (
        (0, 'No'),
        (1, 'Yes')
    )
    age = models.IntegerField()
    sex = models.IntegerField(choices=SEX)
    cp = models.IntegerField(choices=CP, verbose_name='Chest Pain Type')
    trestbps = models.IntegerField(verbose_name='Resting Blood Pressure (mmHg)')
    chol = models.IntegerField(verbose_name='Serum Cholestoral (mg/dl)')
    fbs = models.IntegerField(choices=FBS, verbose_name='Fasting Blood Sugar > 120 mg/dl')
    restecg = models.IntegerField(choices=RESTECG, verbose_name='Resting Electrocardiographic Results')
    thalach = models.IntegerField(verbose_name='Maximum Heart Rate')
    exang = models.IntegerField(choices=EXANG, verbose_name='Exercise Induced Angina')
    oldpeak = models.IntegerField(verbose_name='ST Depression (mmHg)')
    slope = models.IntegerField(choices=SLOPE, verbose_name='Slope of Peak Exercise ST Segment')
    ca = models.IntegerField(verbose_name='Number of Vessels Colored by Flourosopy')
    thal = models.IntegerField(choices=THAL, verbose_name='Thalassemia')
    target = models.IntegerField(choices=TARGET)
    pos = models.FloatField()
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    createdAt = models.DateTimeField(auto_now_add=True)

DashBoard/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import History


class NewUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "first_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        if commit:
            user.save()
        return user


class HealthCheckForm(forms.ModelForm):

    class Meta:
        model = History
        fields = '__all__'

DashBoard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout 
from django.contrib import messages
from django.views.generic import View, ListView
from .forms import *
import pickle
import numpy as np
from .models import History
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

model = pickle.load(open('model.pkl', 'rb'))


# Create your views here.

class StaffRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):

    def test_func(self):
        return self.request.user.is_staff


def index(request):
    if not request.user.is_authenticated:
        return render(request, template_name='auth/home.html')
    return redirect('login')


class Login(View):

    def get(self, request):
        form = AuthenticationForm()
        return render(request=request, template_name="auth/login.html", context={"form": form})

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # messages.info(request, f"You are now logged in as {username}.")
                return redirect('dashboard')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
        return render(request=request, template_name="auth/login.html", context={"form": form})


class Register(View):
    def get(self, request):
        form = NewUserForm()
        return render(request=request, template_name="auth/register.html", context={"form": form})

    def post(self, request):
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.info(request, f"You are now logged in as {username}.")
                    return redirect(index)
        else:
            messages.error(request, "Invalid username or password.")
            return render(request=request, template_name="auth/register.html", context={"form": form})


class Logout(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect(index)


class CheckHealth(LoginRequiredMixin, View):
    def get(self, request):
        form = HealthCheckForm()
        return render(request=request, template_name="main/checkhealth.html", context={"form": form})

    def post(self, request):
        features = []
        for key, value in request.POST.items():
            features.append(value)
        features = [float(i) for i in features[1:]]

        array_features = np.array([features])
        prediction = model.predict(array_features)
        x = model.predict_proba(array_features)
        pos = x[0][1]
        pos = pos * 100

        data = request.POST.copy()
        data['pos'] = round(pos, 2)
        data['target'] = prediction[0]
        data['user'] = request.user.id
        form = HealthCheckForm(data)

        if form.is_valid():
            form.save()
            if pos > 70:
                messages.error(request, f'Probability of having heart disease: {pos}% \n Risk of having heart disease: HIGH')
            elif pos > 40:
                messages.warning(request, f'Probability of having heart disease: {pos}% \n Risk of having heart disease: MEDIUM')
            else:
                messages.success(request, f'Probability of having heart disease: {pos}% \n Risk of having heart disease: LOW')
        else:
            messages.error(request, form.errors)
        return render(request=request, template_name="main/checkhealth.html", context={"form": form})


class HistoryView(LoginRequiredMixin, ListView):
    template_name = 'main/history.html'
    model = History
    context_object_name = 'histories'

    def get_context_data(self, **kwargs):
        context = super(HistoryView, self).get_context_data(**kwargs)
        context.update({
            'histories': History.objects.filter(user=self.request.user),
            'attributes': [i for i in History._meta.get_fields() if i.name not in ['id', 'user']]
        })
        return context

    def get_queryset(self):
        return History.objects.filter(user=self.request.user)


class PrintResult(LoginRequiredMixin, View):
    def get(self, request, pk):
        if not request.user.is_staff:
            try:
                History.objects.get(pk=pk, user=request.user)
            except History.DoesNotExist:
                return redirect('history')
        history = History.objects.get(pk=pk)
        attributes = [i for i in History._meta.get_fields() if i.name not in ['id']]
        if history.pos > 70:
            messages.error(request, f'Probability of having heart disease: {history.pos}% \n Risk of having heart disease: HIGH')
        elif history.pos > 40:
            messages.warning(request, f'Probability of having heart disease: {history.pos}% \n Risk of having heart disease: MEDIUM')
        else:
            messages.success(request, f'Probability of having heart disease: {history.pos}% \n Risk of having heart disease: LOW')
        return render(request=request, template_name="main/printresult.html", context={"history": history, 'attributes': attributes})


class Users(StaffRequiredMixin, ListView):
    template_name = 'admin/users.html'
    context_object_name = 'users'

    def get_context_data(self, **kwargs):
        context = super(Users, self).get_context_data(**kwargs)
        for user in context['users']:
            # add last health check to user
            try:
                user.last_check = History.objects.filter(user=user).latest('createdAt').createdAt
            except Exception:
                user.last_check = 'No history'
        context.update({
            'users': context['users'],
        })
        return context

    def get_queryset(self):
        return User.objects.all()


class UserDetail(StaffRequiredMixin, View):
    def get(self, request, pk):
        user = User.objects.get(id=pk)
        histories = History.objects.filter(user=user)
        attributes = [i for i in History._meta.get_fields() if i.name not in ['id', 'user']]
        return render(request, 'admin/user.html', {'user': user, 'histories': histories, 'attributes': attributes})

DashBoard/templates/main/checkhealth.html
{% extends 'main/nav.html' %}
{% load crispy_forms_tags %}
{% block DashBoard %}
<div class="card-header py-3">
    <h5 class="mb-0 text-center"><strong>Check Health</strong></h5>
</div>
<div class="container">
    <br>
    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.age|as_crispy_field }}
            </div>
            <div class="col-6 helptext">
                {{ form.sex|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.cp|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.trestbps|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.chol|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.fbs|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.restecg|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.thalach|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.exang|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.oldpeak|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.slope|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.ca|as_crispy_field }}
            </div>
        </div>
        {{ form.thal|as_crispy_field }}

        <br>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message.message }}
        </div>
        {% endfor %}
        {% endif %}
        <button type="submit" class="btn btn-success">Check</button>
    </form>
    <br>
</div>
{% endblock %}

DashBoard/templates/main/details.html
{% extends 'main/nav.html' %}
{% load crispy_forms_tags %}
{% block DashBoard %}
<div class="card-header py-3">
    <h5 class="mb-0 text-center"><strong>Check Health</strong></h5>
</div>
<div class="container">
    <br>
    <form action="{% url 'detail' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.age|as_crispy_field }}
            </div>
            <div class="col-6 helptext">
                {{ form.sex|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.cp|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.trestbps|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.chol|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.fbs|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.restecg|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.thalach|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.exang|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.oldpeak|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.slope|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.ca|as_crispy_field }}
            </div>
        </div>
        {{ form.thal|as_crispy_field }}

        <br>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message.message }}
        </div>
        {% endfor %}
        {% endif %}
        <button type="submit" class="btn btn-success">Check</button>
    </form>
    <br>
</div>
{% endblock %}

DashBoard/templates/main/history.html
{% extends 'main/nav.html' %}
{% load crispy_forms_tags %}
{% block DashBoard %}
<div class="card-header py-3">
    <h5 class="mb-0 text-center"><strong>Health check history</strong></h5>
</div>
<div class="container">
    <br>
    <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
            <tr>
                {% for attribute in attributes %}
                <th>{{ attribute.name }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            <!-- for each history print each attributes values -->
            {% if histories %}
            {% for history in histories %}
            <a href="">
                <tr onclick="window.location='/history/{{history.id}}';">
                    <td>{{ history.age }}</td>
                    <td>{{ history.get_sex_display }}</td>
                    <td>{{ history.get_cp_display }}</td>
                    <td>{{ history.trestbps }}</td>
                    <td>{{ history.chol }}</td>
                    <td>{{ history.get_fbs_display }}</td>
                    <td>{{ history.get_restecg_display }}</td>
                    <td>{{ history.thalach }}</td>
                    <td>{{ history.get_exang_display }}</td>
                    <td>{{ history.oldpeak }}</td>
                    <td>{{ history.get_slope_display }}</td>
                    <td>{{ history.ca }}</td>
                    <td>{{ history.get_thal_display }}</td>
                    <td>{{ history.get_target_display }}</td>
                    <td>{{ history.pos }}%</td>
                    <td>{{ history.createdAt|date:"d/m/Y" }}</td>
                </tr>
            </a>


            {% endfor %}

            {% else %}
            <tr>
                <td colspan="12">No data</td>
            </tr>
            {% endif %}


        </tbody>
    </table>
</div>
<script>jQuery(document).ready(function ($) {
        $(".clickable-row").click(function () {
            window.location = $(this).data("href");
        });
    });
</script>

{% endblock %}

DashBoard/templates/main/nav.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<!--Main Navigation-->
<header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
        <div class="position-sticky">
            <h5 style="margin: 20px; text-align: center;">Welcome {{user}} 👋.!</h5>
            <div class="list-group list-group-flush mx-3 mt-4">
                <a href="{% url 'dashboard' %}" class="list-group-item list-group-item-action py-2 ripple">
                    <i class="fas fa-chart-line fa-fw me-3"></i>
                    <span>Check Health</span>
                </a>
                <a href="{% url 'history' %}" class="list-group-item list-group-item-action py-2 ripple">
                    <i class="fas fa-chart-bar fa-fw me-3"></i>
                    <span>Your History</span>
                </a>
                {% if user.is_staff %}
                <a href="{% url 'users' %}" class="list-group-item list-group-item-action py-2 ripple">
                    <i class="fas fa-user fa-fw me-3"></i>
                    <span>Users</span>
                </a>
                {% endif %}
            </div>
        </div>
    </nav>
    <!-- Sidebar -->

    <!-- Navbar -->
    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
        <!-- Container wrapper -->
        <div class="container">
            <!-- Navbar brand -->
            <a class="navbar-brand me-2" href="">
                <!-- <img src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp" height="16" alt="MDB Logo"
                    loading="lazy" style="margin-top: -1px;" /> -->
                <span class="navbar-brand mb-0 h1">Heartella</span>
            </a>

            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                data-mdb-target="#navbarButtonsExample" aria-controls="navbarButtonsExample" aria-expanded="false"
                aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarButtonsExample">
                <!-- Left links -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="">DashBoard</a>
                    </li>
                </ul>
                <!-- Left links -->

                <div class="d-flex align-items-center">
                    <a href="{% url 'logout' %}">
                        <button type="button" class="btn btn-link px-3 me-2">
                            LogOut
                        </button>
                    </a>
                </div>
            </div>
            <!-- Collapsible wrapper -->
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
</header>
<!--Main Navigation-->

<!--Main layout-->
<main style="margin-top: 58px;">
    <div class="container pt-4">
        {% block DashBoard %}
        {% endblock %}
    </div>

</main>
<!--Main layout-->
{% endblock %}

DashBoard/templates/main/printresult.html
{% extends 'main/nav.html' %}
{% load crispy_forms_tags %}
{% block DashBoard %}
<div class="container" style="width: 750px;" id="result">
    <h1 style="text-align: center;"> Heart Disease Prediction Result</h1>
    <hr class="hr-dark">
    <h3>Patient Details:</h3>
    <div class="row">
        <div class="col-6">
            <strong>Username:</strong> {{ user.username }}
        </div>
        <div class="col-6">
            <strong>Name:</strong> {{ user.first_name }}
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <strong>Age:</strong> {{ history.age }}
        </div>
        <div class="col-6">
            <strong>Sex:</strong> {{ history.get_sex_display }}
        </div>
    </div>

    <hr class="hr-dark">
    <h3>Test Values:</h3>

    <div class="row">
        <div class="col-6">
            <strong>Chest Pain Type : </strong> {{ history.get_cp_display }}
        </div>
        <div class="col-6">
            <strong>Resting Blood Pressure (mmHg) : </strong> {{ history.trestbps }}
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <strong>Serum Cholestoral (mg/dl) : </strong> {{ history.chol }}<br>
        </div>
        <div class="col-6">
            <strong>Fasting Blood Sugar > 120 mg/dl : </strong> {{ history.get_fbs_display }}<br>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <strong>Resting Electrocardiographic Results : </strong> {{ history.get_restecg_display }}<br>
        </div>
        <div class="col-6">
            <strong>Maximum Heart Rate : </strong> {{ history.thalach }}<br>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <strong>Exercise Induced Angina : </strong> {{ history.get_exang_display }}<br>
        </div>
        <div class="col-6">
            <strong>ST Depression (mmHg) : </strong> {{ history.oldpeak }}<br>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <strong>Slope of Peak Exercise ST Segment : </strong> {{ history.get_slope_display }}<br>
        </div>
        <div class="col-6">
            <strong>Number of Vessels Colored by Flourosopy : </strong> {{ history.ca }}<br>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <strong>Thalassemia: </strong> {{ history.get_thal_display }}<br>
        </div>
        <div class="col-6">
        </div>
    </div>

    <hr class="hr-dark">
    <h3>Result</h3>

    <h6>Result summary:
        <strong>
            {% if history.target == 2 %}
            You are likely to have heart disease.
            {% else %}
            You are likely not to have heart disease.
            {% endif %}
        </strong>
    </h6>
    </p>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message.message }}
    </div>
    {% endfor %}
    <strong>Tested on: </strong> {{ history.createdAt }}<br>
</div>
<br>
<center>
    <button onclick="window.printDiv() " class="btn btn-primary">Print</button>
</center>
<script>
    function printDiv() {
        var printContents = document.getElementById('result').innerHTML;
        var originalContents = document.body.innerHTML;
        document.body.innerHTML = printContents;
        window.print();
        document.body.innerHTML = originalContents;
    }
</script>
{% endblock %}